runtime: python  # Use Python 3.11 or latest version
entrypoint: gunicorn -b :$PORT app:app
instance_class: F4_1G  # Choose instance size
env: flex
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"
env_variables:
  GOOGLE_CLOUD_PROJECT: "cloud-hackathon-venky"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: 587
  SMTP_USERNAME: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
  GENAI_API_KEY: "AIzaSyAxlDjY7RTAfjWrzlEdnpuEFUiOUj9Pe54"
  TOPIC_NAME: "cron-topic"
  REGION: "us-central1"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
handlers:
  - url: /socket.io/.* 
    script: auto
    secure: always
    login: optional
network:
  session_affinity: true
